//! The bindings `sqlcipher-amalgamation` ships, compiled against the sources it ships.

/// Generated by `sqlite-wasm-rs`'s bindgen setup from SQLCipher's header.
#[expect(
    non_snake_case,
    non_camel_case_types,
    clippy::use_self,
    clippy::unreadable_literal,
    clippy::type_complexity,
    clippy::missing_safety_doc,
    clippy::missing_const_for_fn,
    reason = "bindgen keeps SQLite's C names and shapes"
)]
pub mod sqlcipher {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../sqlcipher/sqlcipher_bindgen.rs"
    ));
}
